#------------------------------------------------------------------------------#
#                                Main settings                                 #
#------------------------------------------------------------------------------#
# Paths to data and results
main_working_directory: /home/bq_aquintero/projects/GRANet/human_atlas_lung/

genome: hg38 #hg19, hg38, or mm9

# Main seurat object save as an RDS file containing counts for the RNA-seq data
# If using multiple datasets, they should be combined into this unique file
seuratobj: "/home/bq_aquintero/projects/GRANet/human_atlas_lung/data/scrna/adult_human_lung_seurat.RDS"
# name of the column in meta.data of seurat with desired annotation
annotCol: "Celltype" 
# List of ArrowFiles for each scATAC-seq dataset 
# (see ArchR documentation on how to create ArrowFiles)
Arrowfiles: 
    lung_SM_ACCPU: /media/ag-cherrmann/projects/10_charite_covid19/subprojects/human_atlas_TF_activity/data/atac/fragments_processed/lung_SM-ACCPU_rep1_fragments.arrow
    lung_SM_A62E9: /media/ag-cherrmann/projects/10_charite_covid19/subprojects/human_atlas_TF_activity/data/atac/fragments_processed/lung_SM-A62E9_rep1_fragments.arrow
    lung_SM_JF1NZ: /media/ag-cherrmann/projects/10_charite_covid19/subprojects/human_atlas_TF_activity/data/atac/fragments_processed/lung_SM-JF1NZ_rep1_fragments.arrow
    lung_SM_A8WNH: /media/ag-cherrmann/projects/10_charite_covid19/subprojects/human_atlas_TF_activity/data/atac/fragments_processed/lung_SM-A8WNH_rep1_fragments.arrow
    
# List of Transcription factor, it should be in Symbols
TF_list:  /home/bq_aquintero/10_charite_covid19/src/charite_covid19/aux/scenic/allTFs_hg38.txt
# TF_list:  "/home/bq_aquintero/projects/mouse_atlas_TF_activity/data/mm_mgi_tfs.txt"
#------------------------------------------------------------------------------#
#                         Pipeline Steps to Run                                #
#------------------------------------------------------------------------------#
phase01_scATAC:
    transferRNAlabels : True
    motifsMatch       : True

phase02_scRNA: 
    pySCENIC : True

phase03_TFactivity:
    specificRegulons : True
    NMF_AUCscores    : True

#------------------------------------------------------------------------------#
#                          GRNBoost settings                                   #
#------------------------------------------------------------------------------#
GRNBoost:
  HVG: "all"



#------------------------------------------------------------------------------#
#            TF activity integrating scRNAseq and scATACseq data               #
#------------------------------------------------------------------------------#
# for building the regulon: The importance represents the relevance that the 
# transcription factor (regulator) has in the prediction of the target. 
tfActity_int:
  cores: 2 # how many cores to use in parallel
  motif_deviation:
    motifMatch_pval: 0.05
  regulons:
    importance_threshold: 50 # in percentile
    promoter_size       : 500000
    min_regulon_size    : 20
  regulonsMethod2:
    cellWithPeak : 0.01 # Minimum fraction of cells for a given cell type, should have this peak to conserve it
    